'use server';
/**
 * @fileOverview A smart assistant that researches the web and answers in audio format.
 *
 * - smartSearchAssistant - A function that handles the research and audio generation process.
 * - SmartSearchAssistantInput - The input type.
 * - SmartSearchAssistantOutput - The return type.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import wav from 'wav';

const SmartSearchAssistantInputSchema = z.object({
  prompt: z.string().describe('The question or topic to research and answer.'),
});
export type SmartSearchAssistantInput = z.infer<typeof SmartSearchAssistantInputSchema>;

const SmartSearchAssistantOutputSchema = z.object({
  answer: z.string().describe('The text answer generated by the assistant.'),
  audioDataUri: z.string().describe('The audio version of the answer as a data URI.'),
});
export type SmartSearchAssistantOutput = z.infer<typeof SmartSearchAssistantOutputSchema>;

const webSearchTool = ai.defineTool(
  {
    name: 'webSearch',
    description: 'Searches the web for real-time information. Use this for current events, facts, or technical details that might have changed recently.',
    inputSchema: z.object({ query: z.string().describe('The search query to use.') }),
    outputSchema: z.string(),
  },
  async (input) => {
    // Simulated web search behavior
    return `Simulated web search result for "${input.query}": Omniferra Smart Assistant found that the requested information is currently being synthesized. In a production environment, this tool would return real-time data from a search engine.`;
  }
);

async function toWav(
  pcmData: Buffer,
  channels = 1,
  rate = 24000,
  sampleWidth = 2
): Promise<string> {
  return new Promise((resolve, reject) => {
    const writer = new wav.Writer({
      channels,
      sampleRate: rate,
      bitDepth: sampleWidth * 8,
    });

    let bufs = [] as any[];
    writer.on('error', reject);
    writer.on('data', function (d) {
      bufs.push(d);
    });
    writer.on('end', function () {
      resolve(Buffer.concat(bufs).toString('base64'));
    });

    writer.write(pcmData);
    writer.end();
  });
}

export async function smartSearchAssistant(input: SmartSearchAssistantInput): Promise<SmartSearchAssistantOutput> {
  return smartSearchAssistantFlow(input);
}

const smartSearchAssistantFlow = ai.defineFlow(
  {
    name: 'smartSearchAssistantFlow',
    inputSchema: SmartSearchAssistantInputSchema,
    outputSchema: SmartSearchAssistantOutputSchema,
  },
  async input => {
    // 1. Research and generate text answer
    const {text} = await ai.generate({
      model: 'googleai/gemini-1.5-flash',
      prompt: `You are a smart research assistant. Research the following and provide a concise, helpful answer: ${input.prompt}`,
      tools: [webSearchTool],
    });

    const answer = text || "I researched your topic but couldn't formulate a specific answer. How else can I help?";

    // 2. Convert text answer to audio
    const { media } = await ai.generate({
      model: 'googleai/gemini-2.5-flash-preview-tts',
      config: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: { voiceName: 'Algenib' },
          },
        },
      },
      prompt: answer,
    });

    if (!media) {
      throw new Error('no audio media returned from model');
    }

    const audioBuffer = Buffer.from(
      media.url.substring(media.url.indexOf(',') + 1),
      'base64'
    );

    const audioDataUri = 'data:audio/wav;base64,' + (await toWav(audioBuffer));

    return {
      answer,
      audioDataUri,
    };
  }
);
